export const planStats = [
  { key: "totalPlans", value: 4 },
  { key: "activePlans", value: 3 },
  { key: "mostPopularPlan", valueKey: "professional" },
  { key: "highestRevenuePlan", valueKey: "enterprise" },
] as const;

export const planRows = [
  {
    id: "1",
    nameKey: "trial",
    monthlyPrice: 0,
    yearlyPrice: 0,
    trialDuration: 14,
    maxUsers: 2,
    maxBranches: 1,
    modules: ["website", "appointments", "customers"],
    supportLevel: "basic",
    status: "active",
    isPopular: false,
    isTrialEnabled: true,
  },
  {
    id: "2",
    nameKey: "starter",
    monthlyPrice: 180,
    yearlyPrice: 1800,
    trialDuration: 7,
    maxUsers: 5,
    maxBranches: 1,
    modules: ["website", "appointments", "customers", "notifications"],
    supportLevel: "standard",
    status: "active",
    isPopular: false,
    isTrialEnabled: true,
  },
  {
    id: "3",
    nameKey: "professional",
    monthlyPrice: 420,
    yearlyPrice: 4200,
    trialDuration: 14,
    maxUsers: 20,
    maxBranches: 3,
    modules: [
      "website",
      "appointments",
      "customers",
      "sessions",
      "notifications",
      "branding",
    ],
    supportLevel: "priority",
    status: "active",
    isPopular: true,
    isTrialEnabled: true,
  },
  {
    id: "4",
    nameKey: "enterprise",
    monthlyPrice: 950,
    yearlyPrice: 9500,
    trialDuration: 0,
    maxUsers: 100,
    maxBranches: 20,
    modules: [
      "website",
      "appointments",
      "customers",
      "sessions",
      "notifications",
      "branding",
      "permissions",
      "domains",
    ],
    supportLevel: "dedicated",
    status: "inactive",
    isPopular: true,
    isTrialEnabled: false,
  },
] as const;

export const planFilters = ["active", "inactive", "trialEnabled", "popular"] as const;
