import { userRows } from "../users-data";

export const userDetailsById = {
  "1": {
    ...userRows[0],
    avatarInitials: "SL",
    mobile: "+972-54-220-1104",
    accessLevel: "fullPlatform",
    assignedRole: "superAdmin",
    twoFactorEnabled: true,
    lastActivity: "2026-04-27",
    directPermissions: ["manageCenters", "manageSubscriptions", "manageUsers"],
    restrictedAreas: ["billingExports"],
    responsibilities: ["subscriptionApprovals", "domainVerification", "supportEscalations"],
    notes: "Primary platform operator for tenant lifecycle and subscription exceptions.",
  },
  "2": {
    ...userRows[1],
    avatarInitials: "AH",
    mobile: "+972-52-880-3412",
    accessLevel: "supportOperations",
    assignedRole: "support",
    twoFactorEnabled: true,
    lastActivity: "2026-04-26",
    directPermissions: ["viewCenters", "manageSupportTickets"],
    restrictedAreas: ["billing", "platformSettings"],
    responsibilities: ["supportTickets", "domainVerification", "salesFollowUp"],
    notes: "Handles daily center support and DNS verification follow-up.",
  },
  "3": {
    ...userRows[2],
    avatarInitials: "MC",
    mobile: "+972-50-441-9088",
    accessLevel: "limitedCommercial",
    assignedRole: "sales",
    twoFactorEnabled: false,
    lastActivity: "2026-04-20",
    directPermissions: [],
    restrictedAreas: ["billing", "userManagement", "platformSettings"],
    responsibilities: ["salesFollowUp", "subscriptionApprovals"],
    notes: "Pending account. Requires 2FA enrollment before full commercial access.",
  },
  "4": {
    ...userRows[3],
    avatarInitials: "DN",
    mobile: "+972-58-620-7719",
    accessLevel: "financeOnly",
    assignedRole: "finance",
    twoFactorEnabled: true,
    lastActivity: "2026-04-24",
    directPermissions: ["viewSubscriptions", "approveInvoices"],
    restrictedAreas: ["domainVerification", "userManagement"],
    responsibilities: ["subscriptionApprovals"],
    notes: "Responsible for billing review, plan exceptions, and finance approvals.",
  },
  "5": {
    ...userRows[4],
    avatarInitials: "NB",
    mobile: "+972-53-117-4040",
    accessLevel: "readOnly",
    assignedRole: "viewer",
    twoFactorEnabled: false,
    lastActivity: "2026-03-29",
    directPermissions: [],
    restrictedAreas: ["billing", "userManagement", "domainVerification", "platformSettings"],
    responsibilities: ["supportTickets"],
    notes: "Suspended read-only account retained for audit review.",
  },
} as const;

export type UserDetails = (typeof userDetailsById)[keyof typeof userDetailsById];

export const activityTimelineById = {
  "1": [
    { key: "userCreated", date: "2026-01-04" },
    { key: "roleChanged", date: "2026-02-08" },
    { key: "permissionUpdated", date: "2026-04-12" },
    { key: "lastLogin", date: "2026-04-27" },
    { key: "passwordReset", date: "2026-04-27" },
  ],
  "2": [
    { key: "userCreated", date: "2026-01-18" },
    { key: "permissionUpdated", date: "2026-03-10" },
    { key: "passwordReset", date: "2026-04-11" },
    { key: "roleChanged", date: "2026-04-18" },
    { key: "lastLogin", date: "2026-04-26" },
  ],
  "3": [
    { key: "userCreated", date: "2026-04-20" },
    { key: "roleChanged", date: "2026-04-20" },
    { key: "permissionUpdated", date: "2026-04-21" },
    { key: "passwordReset", date: "2026-04-22" },
    { key: "lastLogin", date: "2026-04-20" },
  ],
  "4": [
    { key: "userCreated", date: "2026-02-03" },
    { key: "roleChanged", date: "2026-02-03" },
    { key: "permissionUpdated", date: "2026-03-22" },
    { key: "lastLogin", date: "2026-04-24" },
    { key: "passwordReset", date: "2026-04-24" },
  ],
  "5": [
    { key: "userCreated", date: "2026-02-17" },
    { key: "lastLogin", date: "2026-03-29" },
    { key: "permissionUpdated", date: "2026-04-01" },
    { key: "roleChanged", date: "2026-04-02" },
    { key: "passwordReset", date: "2026-04-03" },
  ],
} as const;
